[package]
name = "python-starter"
version = "0.1.0"
authors = ["curekoshimizu <shugo@manabe.mail-box.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "0.3"
is_executable = "1.0.1"
